CREATE TABLE t_usuario (
    id_usuario NUMBER(5) NOT NULL CONSTRAINT PK_USUARIO PRIMARY KEY,
    nm_usuario VARCHAR2(100) NOT NULL,
    ds_email VARCHAR2(150) NOT NULL UNIQUE,
    ds_senha VARCHAR2(255) NOT NULL,
    dt_nascimento DATE NOT NULL
);

CREATE TABLE t_ideias (
    id_ideia NUMBER(5) NOT NULL CONSTRAINT PK_IDEIAS PRIMARY KEY,
    id_usuario NUMBER(5) NOT NULL,
    nm_ideia VARCHAR2(255) NOT NULL,
    ds_descricao VARCHAR2(4000) NOT NULL,
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES t_usuario(id_usuario)
);

CREATE TABLE t_servicos (
    id_servico NUMBER(5) NOT NULL CONSTRAINT PK_SERVICOS PRIMARY KEY,
    id_usuario NUMBER(5) NOT NULL,
    nm_servico VARCHAR2(255) NOT NULL,
    ds_servico VARCHAR2(4000) NOT NULL,
    tipo_servico VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_USUARIO_SERVICOS FOREIGN KEY (id_usuario) REFERENCES T_USUARIO(id_usuario)
);

CREATE TABLE t_ecobiblioteca (
    id_energia NUMBER(5) NOT NULL CONSTRAINT PK_ECOBIBLIOTECA PRIMARY KEY,
    id_servico NUMBER(5) NOT NULL,
    tipo_energia VARCHAR2(255) NOT NULL,
    ds_energia VARCHAR2(1000) NOT NULL,
    CONSTRAINT FK_ECO_SERVICOS FOREIGN KEY (id_servico) REFERENCES t_servicos(id_servico)
);

CREATE TABLE t_dicas (
    id_dica NUMBER(5) NOT NULL CONSTRAINT PK_DICAS PRIMARY KEY,
    id_servico  NUMBER(5) NOT NULL,
    nm_dica VARCHAR2(255) NOT NULL,
    ds_dica VARCHAR2(4000) NOT NULL,
    link_dica VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_DICAS_SERVICOS FOREIGN KEY (id_servico) REFERENCES t_servicos(id_servico)
);

CREATE TABLE t_comentarios (
    id_comentario NUMBER(5) NOT NULL CONSTRAINT PK_COMENTARIOS PRIMARY KEY,
    id_ideia NUMBER(5) NOT NULL,
    id_usuario NUMBER(5) NOT NULL,
    ds_comentario VARCHAR2(4000) NOT NULL,
    CONSTRAINT fk_comentarios_ideia FOREIGN KEY (id_ideia) REFERENCES t_ideias(id_ideia),
    CONSTRAINT fk_comentarios_usuario FOREIGN KEY (id_usuario) REFERENCES t_usuario(id_usuario)
);

CREATE TABLE t_empresas (
    id_empresa NUMBER(5) NOT NULL CONSTRAINT PK_EMPRESAS PRIMARY KEY,
    id_servico NUMBER(5) NOT NULL,
    nm_empresa VARCHAR2(255) NOT NULL,
    nr_cnpj VARCHAR2(18) NOT NULL UNIQUE,
    ds_descricao VARCHAR2(4000) NOT NULL,
    CONSTRAINT FK_EMPRESAS_SERVICOS FOREIGN KEY (id_servico) REFERENCES t_servicos(id_servico)
);

CREATE TABLE t_consumo_energia (
    id_consumo NUMBER(5) NOT NULL CONSTRAINT PK_CONSUMO PRIMARY KEY,
    id_servico NUMBER(5) NOT NULL,
    previsao_energia NUMBER(4, 1) NOT NULL,
    condicao_climatica VARCHAR2(50) NOT NULL,
    horario NUMBER(2) NOT NULL,
    data_previsao DATE NOT NULL,
    CONSTRAINT FK_CONSUMO_SERVICOS FOREIGN KEY (id_servico) REFERENCES t_servicos(id_servico)
);

CREATE TABLE t_politicas (
    id_politica NUMBER(5) NOT NULL CONSTRAINT PK_POLITICAS PRIMARY KEY,
    id_consumo NUMBER(5) NOT NULL,
    nm_politica VARCHAR2(50) NOT NULL,
    nm_setor VARCHAR2(100) NOT NULL,
    reducao_energia NUMBER(3, 1) NOT NULL,
    dt_inicio DATE NOT NULL,
    dt_termino DATE,
    CONSTRAINT FK_POLITICAS_CONSUMO FOREIGN KEY (id_consumo) REFERENCES t_consumo_energia(id_consumo)
);

CREATE SEQUENCE SQ_T_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_IDEIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_SERVICOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_ECOBIBLIOTECA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_DICAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_COMENTARIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_EMPRESAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_CONSUMO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SQ_T_POLITICAS START WITH 1 INCREMENT BY 1 NOCACHE;